[package]
name = "diesel_course"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
diesel = { version = "2.2.4", features = ["postgres", "chrono"] }
diesel_migrations = "2.2.0"
dotenvy = "0.15.7"
eyre = "0.6.12"
